# Quarterly Report Workflow
# Multi-agent orchestration for comprehensive quarterly reporting

name: quarterly-report
description: "Automated quarterly report generation with data analysis and executive summary"
version: "1.0"

# Workflow metadata
metadata:
  category: reporting
  estimated_duration: "3-5 hours"
  requires_approval: true
  slack_channel: "#reports"
  schedule: "0 9 1 1,4,7,10 *"  # 1st day of each quarter at 9 AM

# Trigger conditions
triggers:
  keywords:
    - 분기 보고서
    - 분기 리포트
    - quarterly report
    - Q1 report
    - Q2 report
    - Q3 report
    - Q4 report
  patterns:
    - "(분기|quarterly).*(보고서|report|리포트)"
    - "(Q[1-4]).*(보고서|report)"
  scheduled:
    cron: "0 9 1 1,4,7,10 *"

# Input requirements
inputs:
  required:
    - quarter: string  # Q1, Q2, Q3, Q4
    - year: number
    - departments: array
  optional:
    - focus_areas: array
    - comparison_periods: array

# Agent orchestration
agents:
  # Phase 1: Data Collection (Parallel)
  - stage: data_collection
    parallel: true
    timeout: 60m
    agents:
      - agent: scientist
        tier: MEDIUM
        task: |
          재무 데이터 수집 및 분석
          - 매출 데이터
          - 비용 분석
          - 수익성 지표
        outputs:
          - financial_metrics

      - agent: scientist-low
        tier: LOW
        task: |
          운영 데이터 수집
          - 생산성 지표
          - 프로젝트 현황
          - 리소스 활용률
        outputs:
          - operational_metrics

      - agent: researcher
        tier: MEDIUM
        task: |
          시장 및 경쟁사 데이터 수집
          - 시장 동향
          - 경쟁사 동향
          - 산업 벤치마크
        outputs:
          - market_analysis

  # Phase 2: Deep Analysis
  - stage: analysis
    agent: scientist-high
    tier: HIGH
    task: |
      종합 분석 수행
      - 전분기 대비 성과 분석
      - 전년 동기 대비 분석
      - 트렌드 및 이상치 감지
      - 예측 모델링
    timeout: 45m
    inputs:
      - financial_metrics
      - operational_metrics
      - market_analysis
    outputs:
      - comprehensive_analysis
      - key_insights
      - forecasts

  # Phase 3: Visualization
  - stage: visualization
    agent: designer
    tier: MEDIUM
    task: |
      데이터 시각화 제작
      - 핵심 지표 차트
      - 트렌드 그래프
      - 비교 분석 다이어그램
      - 인포그래픽
    timeout: 40m
    inputs:
      - comprehensive_analysis
    outputs:
      - charts
      - infographics

  # Phase 4: Report Writing
  - stage: writing
    agent: writer
    tier: LOW
    task: |
      보고서 작성
      - 경영진 요약 (Executive Summary)
      - 부서별 성과 섹션
      - 핵심 성과 지표 (KPI) 해설
      - 다음 분기 전망
    timeout: 60m
    inputs:
      - key_insights
      - forecasts
      - charts
    outputs:
      - draft_report

  # Phase 5: Quality Review
  - stage: review
    agent: critic
    tier: HIGH
    task: |
      보고서 품질 검토
      - 데이터 정확성 검증
      - 논리적 일관성 확인
      - 표현 명확성 검토
      - 경영진 관점 적합성
    timeout: 30m
    inputs:
      - draft_report
      - comprehensive_analysis
    outputs:
      - review_feedback
      - final_report

  # Phase 6: Approval
  - stage: approval
    type: sequential_approval
    approvers:
      - department_heads  # First round
      - finance_director  # Second round
      - c_level          # Final round
    timeout: 72h
    slack_notification: true

  # Phase 7: Distribution
  - stage: distribution
    agent: executor-low
    tier: LOW
    task: |
      보고서 배포
      - 이해관계자 이메일 발송
      - 사내 포털 업로드
      - 아카이브 저장
      - Slack 공지
    timeout: 15m
    requires_approval: true

# Output formats
outputs:
  formats:
    - type: pdf
      name: "Q{quarter}_{year}_Quarterly_Report.pdf"
    - type: pptx
      name: "Q{quarter}_{year}_Executive_Presentation.pptx"
    - type: xlsx
      name: "Q{quarter}_{year}_Data_Appendix.xlsx"
  destinations:
    - slack: "#reports"
    - email: "executives@company.com"
    - storage: "/reports/quarterly/{year}/"

# Success criteria
success_criteria:
  - all_data_collected: true
  - analysis_complete: true
  - visualizations_created: true
  - report_approved: true
  - distribution_complete: true

# Quality gates
quality_gates:
  - gate: data_quality
    check: "Missing data < 5%"
  - gate: chart_accuracy
    check: "All charts match source data"
  - gate: executive_summary
    check: "Summary < 2 pages"

# Rollback procedure
rollback:
  on_failure:
    - save_progress: true
    - notify_team: "#reports"
    - create_ticket: true
  steps:
    - "Archive partial work"
    - "Document failure point"
    - "Notify stakeholders of delay"
    - "Schedule retry"

# Scheduling
schedule:
  quarterly:
    Q1: "April 1"
    Q2: "July 1"
    Q3: "October 1"
    Q4: "January 1"
  deadline_days: 10
  reminder_days: [7, 3, 1]

# Notifications
notifications:
  on_start:
    slack: "#reports"
    message: ":chart_with_upwards_trend: Q{quarter} {year} 분기 보고서 생성 시작"
  on_data_ready:
    slack: "#reports"
    message: ":white_check_mark: 데이터 수집 완료 - 분석 단계 진입"
  on_review_needed:
    slack: "@{reviewer}"
    message: ":eyes: 분기 보고서 검토 요청"
  on_complete:
    slack: "#reports"
    message: ":tada: Q{quarter} {year} 분기 보고서 완료 및 배포됨"
  on_failure:
    slack: "#reports"
    message: ":warning: 분기 보고서 생성 실패 - {error}"
