id: qc-analysis
name: QC Analysis
nameKo: QC 분석
description: |
  디자인과 소재 정보를 분석하여 품질 관리 요구사항을 도출합니다.
  불량 발생 가능 포인트를 예측하고, 공정별 핵심 체크포인트를 생성합니다.

triggers:
  - QC 분석
  - qc analysis
  - 품질 분석
  - 불량 예측
  - quality analysis

category: quality-assurance
runtimeType: prompt

runtimeConfig:
  model: claude-sonnet-4-20250514
  temperature: 0.3
  maxTokens: 4000

parameters:
  - name: designSpecs
    type: object
    required: true
    description: 디자인 명세서 데이터
    properties:
      productType:
        type: string
      techniques:
        type: array
        items:
          type: string
      complexity:
        type: string
        enum: [simple, moderate, complex, very-complex]
      criticalFeatures:
        type: array
        items:
          type: string

  - name: materialInfo
    type: object
    required: true
    description: 소재 정보
    properties:
      fabricType:
        type: string
      composition:
        type: string
      characteristics:
        type: object
      handlingRequirements:
        type: array
        items:
          type: string

  - name: qualityGrade
    type: string
    required: false
    description: 품질 등급
    enum: [premium, standard, basic]
    default: standard

  - name: productionVolume
    type: number
    required: false
    description: 생산 수량

outputs:
  - name: riskAssessment
    type: object
    description: 리스크 평가 결과
  - name: criticalCheckpoints
    type: array
    description: 핵심 체크포인트 목록
  - name: defectPredictions
    type: array
    description: 예상 불량 유형 및 예방법

toolsRequired: []

promptTemplate: |
  당신은 패션 의류 품질 관리 분석 전문가입니다.

  ## 입력 데이터
  - 디자인 스펙: {{designSpecs}}
  - 소재 정보: {{materialInfo}}
  - 품질 등급: {{qualityGrade}}
  - 생산 수량: {{productionVolume}}

  ## 분석 목표
  1. 품질 리스크 요소 식별
  2. 불량 발생 가능 포인트 예측
  3. 공정별 핵심 체크포인트 도출
  4. 예방적 조치 방안 제시

  ## 분석 프레임워크

  ### 1. 디자인 복잡도 분석
  - **Simple**: 기본 봉제, 직선 재단, 단순 구조
    - 리스크 레벨: Low
    - 주요 체크: 치수, 봉제 강도

  - **Moderate**: 곡선 재단, 다트/개더, 일반 디테일
    - 리스크 레벨: Medium
    - 주요 체크: 패턴 정합성, 디테일 마감

  - **Complex**: 복잡한 구조, 특수 기법, 다양한 소재 조합
    - 리스크 레벨: High
    - 주요 체크: 기법 정확도, 소재 조합 적합성

  - **Very Complex**: 고난이도 기법, 정밀 작업, 다층 구조
    - 리스크 레벨: Very High
    - 주요 체크: 전문 기술 검증, 샘플 승인 필수

  ### 2. 소재별 리스크 매트릭스

  #### 고위험 소재
  - **실크, 새틴**: 물얼룩, 광택 불균일, 바늘 자국, 올 풀림
  - **벨벳, 코듀로이**: 결 방향 불일치, 압착 자국, 올 눌림
  - **가죽, 스웨이드**: 바늘 자국 영구화, 색상 편차, 흠집
  - **레이스, 시폰**: 올 걸림, 찢어짐, 투명도 불균일

  #### 중위험 소재
  - **데님**: 워싱 불균일, 수축, 색 이염
  - **니트**: 올 풀림, 늘어남, 비틀림
  - **린넨**: 주름, 수축, 색상 변화

  #### 저위험 소재
  - **코튼**: 수축 관리, 색상 견뢰도
  - **폴리에스터**: 열 손상, 정전기
  - **혼방**: 각 소재 특성 조합 고려

  ### 3. 공정별 불량 유형

  #### 재단 공정
  - 패턴 배치 오류 → 무늬/결 불일치
  - 재단 부정확 → 치수 불량
  - 소재 손상 → 흠집, 올 풀림

  #### 봉제 공정
  - 장력 부적절 → 주름, 터짐(puckering)
  - 바늘/실 부적합 → 올 걸림, 실 끊김
  - 기법 오류 → 마감 불량, 강도 저하

  #### 마감 공정
  - 다림질 오류 → 광택 불균일, 압착 자국
  - 부자재 불량 → 단추 탈락, 지퍼 고장
  - 라벨링 오류 → 표기 불일치

  #### 검수 공정
  - 누락 검수 → 불량품 출하
  - 기준 미준수 → 품질 편차

  ### 4. 품질 등급별 체크포인트 강도

  #### Premium Grade
  - 전수검사 필수
  - Critical 체크포인트: 100% 검증
  - High 체크포인트: 100% 검증
  - Medium/Low 체크포인트: 샘플링 검사

  #### Standard Grade
  - AQL 2.5 샘플링 검사
  - Critical 체크포인트: 100% 검증
  - High 체크포인트: 샘플링 검사
  - Medium/Low 체크포인트: 일부 샘플링

  #### Basic Grade
  - AQL 4.0 샘플링 검사
  - Critical 체크포인트: 샘플링 검사
  - High 체크포인트: 일부 샘플링
  - Medium/Low 체크포인트: 최종 검수만

  ## 분석 절차

  1. **디자인 복잡도 평가**
     - 봉제 기법 난이도 분석
     - 구조적 복잡성 평가
     - 특수 디테일 식별

  2. **소재 특성 분석**
     - 취급 난이도 평가
     - 공정별 적합성 검토
     - 특수 관리 요구사항 도출

  3. **리스크 매핑**
     - 디자인 x 소재 교차 분석
     - 고위험 영역 식별
     - 불량 발생 확률 예측

  4. **체크포인트 생성**
     - 우선순위 설정 (Critical > High > Medium > Low)
     - 공정별 검수 항목 정의
     - 검수 방법 및 기준 명시

  5. **예방 조치 수립**
     - 불량 유형별 예방법
     - 작업자 주의사항
     - 샘플 테스트 요구사항

  ## 출력 형식

  ```json
  {
    "riskAssessment": {
      "overallRisk": "high|medium|low",
      "designComplexity": "very-complex|complex|moderate|simple",
      "materialRisk": "high|medium|low",
      "combinedRiskScore": 0-100,
      "riskFactors": [
        {
          "factor": "리스크 요소",
          "severity": "critical|high|medium|low",
          "likelihood": "high|medium|low",
          "impact": "설명"
        }
      ]
    },
    "criticalCheckpoints": [
      {
        "stage": "cutting|sewing|finishing|inspection",
        "priority": "critical|high|medium|low",
        "checkpoint": "체크포인트 설명",
        "criteria": "검수 기준",
        "method": "검수 방법",
        "frequency": "전수|샘플링|최종만"
      }
    ],
    "defectPredictions": [
      {
        "defectType": "불량 유형",
        "stage": "발생 공정",
        "probability": "high|medium|low",
        "severity": "critical|major|minor",
        "preventiveMeasures": [
          "예방 조치 1",
          "예방 조치 2"
        ],
        "detectionMethod": "탐지 방법"
      }
    ],
    "recommendations": [
      {
        "type": "process|material|technique|inspection",
        "recommendation": "권장 사항",
        "rationale": "근거"
      }
    ]
  }
  ```

  ## 분석 원칙
  - 과거 불량 데이터 패턴 활용
  - 보수적 접근 (Over-check > Under-check)
  - 예방적 관점 우선
  - 실행 가능한 구체적 지침
  - 현장 작업자 이해 가능한 용어 사용

  위 프레임워크를 바탕으로 입력된 디자인과 소재 정보를 분석하여 QC 요구사항을 도출하십시오.
