#!/bin/bash
set -e

echo "💬 Slack Bot Setup for Nubabel"
echo "==============================="
echo ""

echo "📋 Step 1: Create Slack App"
echo "----------------------------------------"
echo "1. Open: https://api.slack.com/apps"
echo "2. Click 'Create New App'"
echo "3. Choose 'From scratch'"
echo "4. App Name: Nubabel Bot"
echo "5. Pick a workspace: [your workspace]"
echo "6. Click 'Create App'"
echo ""
read -p "Press Enter when app is created..."

echo ""
echo "📋 Step 2: Enable Socket Mode"
echo "----------------------------------------"
echo "1. Go to: Settings → Socket Mode"
echo "2. Toggle 'Enable Socket Mode' to ON"
echo "3. Token Name: nubabel-socket"
echo "4. Click 'Generate'"
echo "5. Copy the token (starts with xapp-)"
echo ""
read -p "Paste App Token (xapp-...): " SLACK_APP_TOKEN

echo ""
echo "📋 Step 3: Add Bot Scopes"
echo "----------------------------------------"
echo "1. Go to: Features → OAuth & Permissions"
echo "2. Under 'Scopes' → 'Bot Token Scopes', add:"
echo "   - app_mentions:read"
echo "   - chat:write"
echo "   - users:read"
echo "   - im:history"
echo "3. Click 'Install to Workspace'"
echo "4. Authorize the app"
echo "5. Copy Bot User OAuth Token (starts with xoxb-)"
echo ""
read -p "Paste Bot Token (xoxb-...): " SLACK_BOT_TOKEN

echo ""
echo "📋 Step 4: Get Signing Secret"
echo "----------------------------------------"
echo "1. Go to: Settings → Basic Information"
echo "2. Under 'App Credentials', find 'Signing Secret'"
echo "3. Click 'Show' and copy"
echo ""
read -p "Paste Signing Secret: " SLACK_SIGNING_SECRET

echo ""
echo "📋 Step 5: Enable Event Subscriptions"
echo "----------------------------------------"
echo "1. Go to: Features → Event Subscriptions"
echo "2. Toggle 'Enable Events' to ON"
echo "3. Subscribe to bot events:"
echo "   - app_mention"
echo "   - message.im"
echo "4. Save Changes"
echo ""
read -p "Press Enter when events are configured..."

echo ""
echo "📋 Step 6: Update Railway Environment Variables"
echo "----------------------------------------"
railway variables set SLACK_BOT_TOKEN="$SLACK_BOT_TOKEN"
railway variables set SLACK_APP_TOKEN="$SLACK_APP_TOKEN"
railway variables set SLACK_SIGNING_SECRET="$SLACK_SIGNING_SECRET"

echo ""
echo "✅ Slack Bot setup complete!"
echo ""
echo "Next steps:"
echo "1. Restart your Railway deployment"
echo "2. Mention @Nubabel Bot in Slack to test"
echo "==============================="
