#!/bin/bash
set -e

echo "🔐 Google OAuth Setup for Nubabel"
echo "=================================="
echo ""

echo "📋 Step 1: Create Google Cloud Project"
echo "----------------------------------------"
echo "1. Open: https://console.cloud.google.com/"
echo "2. Click 'Select a project' → 'New Project'"
echo "3. Project name: 'Nubabel Production'"
echo "4. Click 'Create'"
echo ""
read -p "Press Enter when project is created..."

echo ""
echo "📋 Step 2: Enable Google+ API"
echo "----------------------------------------"
echo "1. Go to: https://console.cloud.google.com/apis/library"
echo "2. Search for 'Google+ API'"
echo "3. Click 'Enable'"
echo ""
read -p "Press Enter when API is enabled..."

echo ""
echo "📋 Step 3: Configure OAuth Consent Screen"
echo "----------------------------------------"
echo "1. Go to: https://console.cloud.google.com/apis/credentials/consent"
echo "2. User Type: External"
echo "3. App name: Nubabel"
echo "4. User support email: your-email@nubabel.com"
echo "5. Developer contact: your-email@nubabel.com"
echo "6. Add scope: .../auth/userinfo.email"
echo "7. Add scope: .../auth/userinfo.profile"
echo "8. Save and Continue"
echo ""
read -p "Press Enter when consent screen is configured..."

echo ""
echo "📋 Step 4: Create OAuth 2.0 Credentials"
echo "----------------------------------------"
echo "1. Go to: https://console.cloud.google.com/apis/credentials"
echo "2. Click 'Create Credentials' → 'OAuth client ID'"
echo "3. Application type: Web application"
echo "4. Name: Nubabel Production"
echo "5. Authorized redirect URIs:"
echo "   - https://auth.nubabel.com/auth/google/callback"
echo "6. Click 'Create'"
echo ""
read -p "Press Enter when credentials are created..."

echo ""
echo "📋 Step 5: Copy Credentials"
echo "----------------------------------------"
echo "Copy the following and save securely:"
echo ""
echo "Client ID: [from Google Console]"
read -p "Paste Client ID: " GOOGLE_CLIENT_ID
echo ""
echo "Client Secret: [from Google Console]"
read -p "Paste Client Secret: " GOOGLE_CLIENT_SECRET

echo ""
echo "📋 Step 6: Update Railway Environment Variables"
echo "----------------------------------------"
railway variables set GOOGLE_CLIENT_ID="$GOOGLE_CLIENT_ID"
railway variables set GOOGLE_CLIENT_SECRET="$GOOGLE_CLIENT_SECRET"
railway variables set GOOGLE_REDIRECT_URI="https://auth.nubabel.com/auth/google/callback"

echo ""
echo "✅ Google OAuth setup complete!"
echo ""
echo "Credentials saved to Railway."
echo "=================================="
