id: trend-scraping
name: Trend Scraping
nameKo: 트렌드 스크래핑
description: |
  다양한 소스에서 패션 트렌드 데이터를 수집하고 정제합니다.
  Google Trends, Instagram, Pinterest, 런웨이 리뷰 등에서
  데이터를 수집하여 구조화된 형태로 반환합니다.

triggers:
  - 트렌드 수집
  - 트렌드 스크래핑
  - trend scraping
  - collect trends
  - 데이터 수집

category: research
runtimeType: prompt

runtimeConfig:
  model: claude-sonnet-4-20250514
  temperature: 0.3
  maxTokens: 4000

parameters:
  - name: sources
    type: array
    items:
      type: string
      enum:
        - google-trends
        - instagram
        - pinterest
        - runway-shows
        - street-style
        - competitor
    required: true
    description: 수집할 데이터 소스

  - name: seasonCode
    type: string
    required: true
    description: 타겟 시즌 (예: 2026SS)

  - name: categories
    type: array
    items:
      type: string
    required: false
    description: 분석할 패션 카테고리

  - name: markets
    type: array
    items:
      type: string
    required: false
    description: 타겟 시장

outputs:
  - name: rawData
    type: object
    description: 수집된 원본 데이터
  - name: processedTrends
    type: array
    description: 정제된 트렌드 목록
  - name: sourcesAnalyzed
    type: array
    description: 분석 완료된 소스 목록

toolsRequired:
  - web__search
  - web__fetch

promptTemplate: |
  당신은 패션 트렌드 데이터 수집 전문가입니다.

  ## 수집 요청
  - 시즌: {{seasonCode}}
  - 소스: {{sources}}
  - 카테고리: {{categories}}
  - 시장: {{markets}}

  ## 수집 지침

  ### 1. Google Trends (google-trends)
  - 패션 관련 검색어 트렌드 분석
  - 시즌 관련 키워드 볼륨 추적
  - 지역별 관심도 차이 파악

  ### 2. Instagram (instagram)
  - 패션 인플루언서 피드 분석
  - 해시태그 트렌드
  - 스타일 트렌드 비주얼 패턴

  ### 3. Pinterest (pinterest)
  - 인기 핀 및 보드 분석
  - 저장율 높은 스타일
  - 색상 및 패턴 트렌드

  ### 4. Runway Shows (runway-shows)
  - 주요 패션위크 컬렉션 분석
  - 디자이너 트렌드 방향
  - 소재 및 실루엣 트렌드

  ### 5. Street Style (street-style)
  - 스트리트 패션 트렌드
  - 실제 소비자 스타일 패턴
  - 지역별 스타일 차이

  ### 6. Competitor (competitor)
  - 경쟁사 신제품 분석
  - 가격 전략
  - 마케팅 메시지

  ## 출력 형식
  수집된 데이터를 다음 JSON 구조로 정리:
  ```json
  {
    "rawData": {
      "[source]": { ... }
    },
    "processedTrends": [
      {
        "name": "트렌드명",
        "source": "출처",
        "category": "카테고리",
        "confidence": 0.85,
        "keywords": ["키워드1", "키워드2"],
        "description": "설명"
      }
    ],
    "sourcesAnalyzed": ["google-trends", "instagram"]
  }
  ```
