id: layout-generation
name: Layout Generation
nameKo: 레이아웃 생성
description: |
  라인시트 레이아웃을 생성합니다.
  제품 정보와 이미지를 배치하고, 레이아웃 스타일에 맞춰
  페이지를 구성하며, 브랜드 일관성을 유지합니다.

triggers:
  - 레이아웃 생성
  - layout generation
  - 라인시트 레이아웃
  - 페이지 구성

category: design
runtimeType: prompt

runtimeConfig:
  model: claude-sonnet-4-20250514
  temperature: 0.4
  maxTokens: 4000

parameters:
  - name: products
    type: array
    required: true
    description: 제품 정보 배열 (SKU, 이미지, 가격 등)

  - name: layoutStyle
    type: string
    required: true
    enum: [grid, list, detailed]
    description: 레이아웃 스타일

  - name: brandInfo
    type: object
    required: true
    description: 브랜드 정보 (로고, 색상, 폰트)
    properties:
      brandName:
        type: string
      logoUrl:
        type: string
      primaryColor:
        type: string
      secondaryColor:
        type: string
      fontFamily:
        type: string

  - name: seasonCode
    type: string
    required: true
    description: 시즌 코드

  - name: preferences
    type: object
    required: false
    description: 레이아웃 선호 설정
    properties:
      showPricing:
        type: boolean
        default: true
      showMaterials:
        type: boolean
        default: true
      showSizing:
        type: boolean
        default: true
      watermark:
        type: string

outputs:
  - name: layoutPages
    type: array
    description: 생성된 페이지별 레이아웃 데이터
  - name: pageCount
    type: number
    description: 총 페이지 수
  - name: layoutMetadata
    type: object
    description: 레이아웃 메타데이터

promptTemplate: |
  당신은 패션 라인시트 레이아웃 디자인 전문가입니다.

  ## 입력 데이터
  - 제품 정보: {{products}}
  - 레이아웃 스타일: {{layoutStyle}}
  - 브랜드 정보: {{brandInfo}}
  - 시즌: {{seasonCode}}
  - 선호 설정: {{preferences}}

  ## 레이아웃 스타일별 가이드

  ### Grid Layout ({{layoutStyle}} == "grid")
  - 페이지당 제품 수: 6개 (2열 x 3행)
  - 제품 이미지: 큰 사이즈 (페이지의 60% 차지)
  - 정보 표시: 간결 (품번, 이름, 가격, 컬러)
  - 여백: 충분한 화이트 스페이스 유지
  - 적합: 많은 제품을 한눈에 보여줄 때

  ### List Layout ({{layoutStyle}} == "list")
  - 페이지당 제품 수: 3-4개 (세로 배치)
  - 제품 이미지: 중간 사이즈 (왼쪽 40%)
  - 정보 표시: 상세 (오른쪽 60% - 전체 스펙)
  - 여백: 정보 간 명확한 구분선
  - 적합: 제품 스펙이 중요할 때

  ### Detailed Layout ({{layoutStyle}} == "detailed")
  - 페이지당 제품 수: 1개
  - 제품 이미지: 대형 (페이지 상단 70%)
  - 정보 표시: 최대 상세 (모든 스펙, 디테일 컷)
  - 여백: 이미지와 텍스트 분리
  - 적합: 고급 제품, 주력 아이템

  ## 페이지 구성 요소

  ### 헤더 (모든 페이지)
  - 브랜드 로고 ({{brandInfo.logoUrl}})
  - 시즌 코드 ({{seasonCode}})
  - 페이지 번호

  ### 제품 정보 카드
  ```
  [제품 이미지]

  품번: {{product.styleNumber}}
  제품명: {{product.name}}
  카테고리: {{product.category}}

  컬러: [컬러칩 이미지]
  사이즈: {{product.sizes}}
  소재: {{product.materials}} (옵션)

  소비자가: {{product.retailPrice}}
  도매가: {{product.wholesalePrice}} (옵션)
  MOQ: {{product.moq}}
  ```

  ### 푸터
  - 연락처 정보
  - 웹사이트
  - 작은 워터마크 (옵션)

  ## 브랜드 일관성
  - 메인 컬러: {{brandInfo.primaryColor}}
  - 서브 컬러: {{brandInfo.secondaryColor}}
  - 폰트: {{brandInfo.fontFamily}}
  - 로고 위치: 좌측 상단 고정

  ## 출력 형식
  ```json
  {
    "layoutPages": [
      {
        "pageNumber": 1,
        "products": [
          {
            "position": "top-left",
            "styleNumber": "KF-2026-001",
            "layout": {
              "imageRect": {"x": 10, "y": 10, "width": 200, "height": 250},
              "textRect": {"x": 10, "y": 265, "width": 200, "height": 100}
            }
          }
        ],
        "header": {
          "logoRect": {"x": 20, "y": 20, "width": 100, "height": 40},
          "seasonText": "2026 S/S",
          "seasonRect": {"x": 650, "y": 30, "width": 100, "height": 20}
        },
        "footer": {
          "contactText": "contact@kyndof.com | www.kyndof.com"
        }
      }
    ],
    "pageCount": 34,
    "layoutMetadata": {
      "layoutStyle": "{{layoutStyle}}",
      "productsPerPage": 6,
      "totalProducts": 200,
      "pageSize": "A4",
      "orientation": "portrait",
      "dpi": 300
    }
  }
  ```

  ## 디자인 원칙
  1. **가독성**: 모든 텍스트는 최소 10pt 이상
  2. **일관성**: 모든 페이지 동일한 그리드 시스템
  3. **계층**: 정보 중요도에 따른 시각적 계층 구조
  4. **여백**: 충분한 화이트 스페이스로 깔끔함 유지
  5. **브랜드**: 브랜드 컬러와 폰트 일관 사용

  위 가이드를 따라 {{products.length}}개 제품의 레이아웃을 생성하세요.
